services:
  - type: web
    name: ytpipeline-stem-separation
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_PASSWORD
        value: CookieRocks
      - key: HOST
        value: 0.0.0.0

